// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package featureflag

import (
	"snapp-featureflag/internal/package/config"
)

// Injectors from wire.go:

func CreateApp() (*App, error) {
	appConfig, err := config.NewAppConfig()
	if err != nil {
		return nil, err
	}
	serveMux, err := NewHttpServeMux()
	if err != nil {
		return nil, err
	}
	app, err := NewApp(appConfig, serveMux)
	if err != nil {
		return nil, err
	}
	return app, nil
}
