// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package featureflag

import (
	"snapp-featureflag/internal/app/featureflag/feature"
	"snapp-featureflag/internal/package/config"
	"snapp-featureflag/internal/package/service/redis"
)

// Injectors from wire.go:

func CreateApp() (*App, error) {
	appConfig, err := config.NewAppConfig()
	if err != nil {
		return nil, err
	}
	cacheServiceImpl, err := redis.NewCacheService(appConfig)
	if err != nil {
		return nil, err
	}
	repositoryImpl := feature.NewRepository(cacheServiceImpl)
	commandHandler := feature.NewCommandHandler(repositoryImpl)
	queryHandler := feature.NewQueryHandler(repositoryImpl)
	apiHandler := NewApiHandler(commandHandler, queryHandler)
	serveMux, err := NewHttpServeMux(apiHandler)
	if err != nil {
		return nil, err
	}
	app, err := NewApp(appConfig, serveMux)
	if err != nil {
		return nil, err
	}
	return app, nil
}
